---
name: clangd-llvm
description: |
  clangd understands your C++ code and adds smart features to your editor: code completion, compile errors,
  go-to-definition and more.
homepage: https://clangd.llvm.org
licenses:
  - Apache-2.0
languages:
  - C
  - C++
categories:
  - LSP

source:
  id: pkg:github/llvm/llvm-project@18.1.3
  asset:
    - target: linux_arm64_gnu
      file: clang+llvm-{{version}}-aarch64-linux-gnu.tar.xz
      bin: clang+llvm-{{version}}-aarch64-linux-gnu/bin//clangd

schemas:
  lsp: vscode:https://raw.githubusercontent.com/clangd/vscode-clangd/master/package.json

bin:
  clangd: "{{source.asset.bin}}"
